#!/bin/bash

TOTAL=$#
if [ $TOTAL -lt 1 ]; then
    exit 1
fi

OPTIONS=$(zenity --width=250 --height=300 --text="" --list --radiolist --hide-header --hide-column=2 --column "" --column "" --column "" TRUE 0 "video to gif" FALSE 1 "extract audio" FALSE 2 "scale" FALSE 3 "rotate" FALSE 4 "cut" FALSE 5 "crop")

BASEDIR=$(dirname $(realpath "$0"))

if [[ "$OPTIONS" == *"0"* ]]; then
    "$BASEDIR"/video2gif "$@"
fi
if [[ "$OPTIONS" == *"1"* ]]; then
    "$BASEDIR"/video2audio "$@"
fi
if [[ "$OPTIONS" == *"2"* ]]; then
    "$BASEDIR"/video-scale "$@"
fi
if [[ "$OPTIONS" == *"3"* ]]; then
    "$BASEDIR"/video-rotate "$@"
fi
if [[ "$OPTIONS" == *"4"* ]]; then
    "$BASEDIR"/video-cut "$@"
fi
if [[ "$OPTIONS" == *"5"* ]]; then
    "$BASEDIR"/video-crop "$@"
fi

exit 0
